### ISSUE TITLE
logAnalyzer - new parametr

### ISSUE THREAD

**Issue by KITT3000** [jtsage/FS_XMLTools#1]
would it be possible to add a parameter `-d` (-default) with the default path to the LOG FS file?

**Comment by jtsage** [comment]
sure.  To make sure I understand what you are asking - provide the `-d` option and it attempts to load %USERPROFILE%\Documents\My Games\FarmingSimulator2022\log.txt ?  

I could probably take it a step further and just read that file by default if there is no file given on the command line or via drag-and-drop, that might be simpler to use from "not the command line"

**Comment by KITT3000** [comment]
yep, I am tired of going to the LOG folder every time, and it is standard, it cannot be changed, so it will greatly speed up the tests

**Comment by jtsage** [comment]
got it.  This one is super easy, give me an hour or two and I'll push it.

**Comment by KITT3000** [comment]
but it seems to me that the parameter will be better because you can additionally set the version of the game, e.g.
`-d 17` ---- `My Games/FarmingSimulator2017/log.txt`
`-d 19` ---- `My Games/FarmingSimulator2019/log.txt`
`-d 22` ---- `My Games/FarmingSimulator2022/log.txt`
`-d 23` ---- `My Games/FarmingSimulator2023/log.txt`

**Comment by jtsage** [comment]
oh!  that's a good idea too.  I'll add that.  It's still gonna default to 22, but if -d ## is present, it'll go for those instead

**Comment by jtsage** [comment]
So, runtime options:

1.) bare program -> read 2022 log

2.) `-d [version]` (or `--detect [version]` option - grab that version of FS log.  Version can be 2 digit or 4 digit. (19 or 2019)

3.) provide a file at the command line / drag-and-drop will read that file instead.
